import { MainLayout } from "@/components/layout/MainLayout";
import { TopicLayout } from "@/components/topics/TopicLayout";
import { TheorySection } from "@/components/topics/TheorySection";
import { VivaQuestions } from "@/components/topics/VivaQuestions";
import { GlassCard } from "@/components/ui/GlassCard";

const VIVA_QS = [
  {
    question: "What is the SLR parsing table?",
    answer: "The SLR table consists of two parts: ACTION[state, terminal] (which can be shift, reduce, accept, or error) and GOTO[state, non-terminal] (the next state after a reduction).",
  },
  {
    question: "When is a grammar SLR(1)?",
    answer: "A grammar is SLR(1) if the constructed table has no conflicts: no state has both shift and reduce actions on the same terminal, and no two reduce actions in the same state with overlapping FOLLOW sets.",
  },
];

export default function SLRTablePage() {
  return (
    <MainLayout title="SLR Parsing Table">
      <TopicLayout
        title="Construction of SLR Parsing Table"
        difficulty="Advanced"
        estimatedTime="60 min"
        description="Build the SLR ACTION and GOTO tables from the canonical LR(0) collection and FOLLOW sets."
        theory={
          <TheorySection
            blocks={[
              { type: "heading", content: "SLR Table Construction" },
              {
                type: "algorithm",
                title: "SLR Table Algorithm",
                content: [
                  "1. Augment grammar: add S' → S",
                  "2. Build canonical LR(0) collection C = {I₀, I₁, ..., Iₙ}",
                  "3. Compute FOLLOW sets for all non-terminals",
                  "4. For each state Iᵢ:",
                  "   a. [A→α•aβ] ∈ Iᵢ and GOTO(Iᵢ,a)=Iⱼ → ACTION[i,a]=shift j",
                  "   b. [A→α•] ∈ Iᵢ, A≠S' → ACTION[i,a]=reduce(A→α) for all a∈FOLLOW(A)",
                  "   c. [S'→S•] ∈ Iᵢ → ACTION[i,$]=accept",
                  "5. GOTO[i,A]=j if GOTO(Iᵢ,A)=Iⱼ",
                  "6. Any undefined entry is an error",
                ],
              },
              {
                type: "example",
                title: "Example SLR Table (Grammar: E→E+T|T, T→T*F|F, F→(E)|id)",
                content: `State | id  +   *   (   )   $   | E   T   F
------+----------------------------+----------
  0   | s5  .   .  s4   .   .   | 1   2   3
  1   |  .  s6  .   .   .  acc  |
  2   |  .  r2  s7  .  r2  r2   |
  3   |  .  r4  r4  .  r4  r4   |
  4   | s5  .   .  s4   .   .   | 8   2   3
  5   |  .  r6  r6  .  r6  r6   |
  6   | s5  .   .  s4   .   .   |     9   3
  7   | s5  .   .  s4   .   .   |         10
  8   |  .  s6  .   .  s11  .   |
  9   |  .  r1  s7  .  r1  r1   |
  10  |  .  r3  r3  .  r3  r3   |
  11  |  .  r5  r5  .  r5  r5   |`,
              },
            ]}
            complexity={{ time: "O(|states| × |grammar symbols|)", space: "O(|states| × |grammar symbols|)" }}
            commonErrors={[
              "Reduce-reduce conflict: two reduce items with overlapping FOLLOW in same state",
              "Shift-reduce conflict: unable to resolve because grammar isn't SLR(1)",
            ]}
          />
        }
        code={<GlassCard className="p-5"><pre className="text-slate-300 text-sm font-mono whitespace-pre-wrap">{`/* SLR table is typically generated by a parser generator tool.
   The construction algorithm is coded in slr_parsing/page.tsx.
   See the theory section for the complete algorithm. */`}</pre></GlassCard>}
        algorithm={
          <TheorySection
            blocks={[
              {
                type: "algorithm",
                title: "Algorithm: SLR Parsing Table Construction",
                content: [
                  "Step 1 — Augment grammar: add production S' → S",
                  "Step 2 — Build canonical LR(0) collection C = {I₀, I₁, ..., Iₙ} using CLOSURE and GOTO",
                  "Step 3 — Compute FOLLOW sets for all non-terminals",
                  "Step 4 — For each state Iᵢ, fill the ACTION table:",
                  "  If [A → α•aβ] ∈ Iᵢ and GOTO(Iᵢ, a) = Iⱼ (a is terminal): ACTION[i, a] = shift j",
                  "  If [A → α•] ∈ Iᵢ and A ≠ S': for each a ∈ FOLLOW(A): ACTION[i, a] = reduce A → α",
                  "  If [S' → S•] ∈ Iᵢ: ACTION[i, $] = accept",
                  "Step 5 — Fill the GOTO table: if GOTO(Iᵢ, A) = Iⱼ (A is non-terminal): GOTO[i, A] = j",
                  "Step 6 — All undefined entries are error entries",
                  "If any cell has more than one action: grammar is not SLR(1)",
                ],
              },
              {
                type: "note",
                content: "SLR conflicts arise when FOLLOW sets are too broad. If a∈FOLLOW(A)∩FOLLOW(B) and both have complete items in the same state, a reduce-reduce conflict occurs.",
              },
            ]}
            complexity={{ time: "O(|G| × |States| × |T|)", space: "O(|States| × (|T| + |NT|))" }}
          />
        }
        visualization={
          <GlassCard className="p-5">
            <h3 className="font-bold text-white mb-4">Conflict Detection</h3>
            <div className="space-y-4">
              {[
                { type: "Shift-Reduce Conflict", color: "amber", desc: "State has [A→α•aβ] AND [B→γ•] where a ∈ FOLLOW(B). Cannot decide: shift a or reduce B→γ?" },
                { type: "Reduce-Reduce Conflict", color: "rose", desc: "State has [A→α•] AND [B→β•] where FOLLOW(A) ∩ FOLLOW(B) ≠ ∅. Cannot decide which production to reduce." },
              ].map(c => (
                <div key={c.type} className={`p-4 rounded-xl bg-${c.color}-500/8 border border-${c.color}-500/20`}>
                  <div className={`text-${c.color}-400 font-semibold mb-1`}>{c.type}</div>
                  <p className="text-slate-300 text-sm">{c.desc}</p>
                </div>
              ))}
            </div>
          </GlassCard>
        }
        practice={<GlassCard className="p-5"><p className="text-slate-300 text-sm">Build the complete SLR table for: S→AA, A→aA|b</p></GlassCard>}
        viva={<VivaQuestions questions={VIVA_QS} />}
      />
    </MainLayout>
  );
}
